
[data]
  database = "sqlite"
  n_workers = 6
  working_dir = "."

[linking]
  max_distance = 100.0
  max_neighbors = 5
  n_workers = 6

[segmentation]
  anisotropy_penalization = 0.0
  max_area = 1000000
  max_noise = 0.4
  min_area = 5000
  min_frontier = 0.0
  n_workers = 6
  threshold = 0.1
  ws_hierarchy = "area"

[tracking]
  appear_weight = -0.005
  bias = 0.0
  disappear_weight = -0.005
  division_weight = 0.0
  link_function = "power"
  method = -1
  n_threads = 0
  overlap_size = 1
  power = 4
  solution_gap = 0.001
  time_limit = 7200
