name: ultrack-flow-field
channels:
  - pytorch
  - gurobi
  - rapidsai
  - conda-forge
  - defaults
dependencies:
  - coin-or-cbc
  - cupy
  - cpuonly
  - gurobi
  - jupyter
  - pip
  - pyqt
  - pytorch
  - pip:
    - napari==0.4.18
    - traccuracy
